accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, StudentCreateView, StreamView, TeacherCreateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('', IndexView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('signup/student/stream/', StreamView.as_view(template_name = "accounts/student_stream.html"), name='student_stream'),
    path('signup/student/<int:stream_pk>/', StudentCreateView.as_view(), name='student_signup'),
    
    path('signup/teacher/stream/', StreamView.as_view(template_name = "accounts/teacher_stream.html"), name='teacher_stream'),
    path('signup/teacher/<int:stream_pk>/', TeacherCreateView.as_view(), name='teacher_signup'),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mylms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", view=HomeView.as_view(),name='home'),
    path('dashboard/', DashboardView, name='dashboard'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('students/', include('students.urls', namespace='students')),
    path('teachers/', include('teachers.urls', namespace='teachers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

students/urls.py
from django.urls import include, path
from .views import (DashboardView,
                    ClassroomDetailView,
                    ResourcesView,
                    AssignmentsView,
                    AssignmentSubmissionCreateView,
                    MyAssignmentView,
                    AssignmentSubmissionDeleteView,
                    joinClassroomView,
                    LeaveClassroomView,
                    view_grade
                    )

app_name = 'students'

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('classroom/<slug:code>/', ClassroomDetailView,name='classroom_detail'),
    path('section/<int:pk>/resources/', ResourcesView, name='resources'),
    path('section/<int:pk>/assignments/', AssignmentsView, name='assignments'),
    path('assignment/<int:pk>/', MyAssignmentView, name='my_assignment'),
    path('assignment/<int:pk>/submit/', AssignmentSubmissionCreateView.as_view(), name='submit_assignment'),
    path('delete-submission/<int:pk>/', AssignmentSubmissionDeleteView.as_view(), name='delete_submission'),
    path('join-new/',joinClassroomView, name='join_classroom'),
    path('leave-classroom/<slug:code>/', LeaveClassroomView,name='leave_classroom'),

    path('view-grade/<int:pk>/', view_grade,name='view_grade'),
]

students/models.py
from django.db import models

# Create your models here.

# class grades(models.Model):
#     classrooms = models.ManyToManyField("Classroom", related_name='students', blank=True)
    
#     class Meta:
#         verbose_name = _("student")
#         verbose_name_plural = _("students")
#         unique_together = ('roll_no', 'current_class')

#     def __str__(self):
#         return self.user.username

#     def get_absolute_url(self):
#         return reverse("Student_detail", kwargs={"pk": self.pk})

students/forms.py
from accounts.models import Classroom,Teacher, Section, Resource,Assignment,AssignmentSubmission
from django import forms

class AssignmentSubmissionForm(forms.ModelForm):
    
    class Meta:
        model = AssignmentSubmission
        fields = ("file",)

class JoinClassroomForm(forms.Form):
    code = forms.CharField(max_length=50, required=True)
    

    

students/views.py
from django.http import HttpResponseRedirect
from django import forms
from django import views
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, DetailView
from accounts.models import Classroom,Teacher,User,Section, Resource,Assignment,AssignmentSubmission, Student
from accounts.passtests import StudentTestMixin, TeacherTestMixin
from .forms import AssignmentSubmissionForm, JoinClassroomForm

# Create your views here.

class DashboardView(StudentTestMixin, TemplateView):
    template_name = "students/dashboard.html"

def ClassroomDetailView(request,code):
    context_dict = {}
    room = get_object_or_404(Classroom, code=code)
    context_dict['classroom'] = room
    return render(request, 'students/classroom_detail.html', context=context_dict)

def ResourcesView(request, pk):
    context_dict = {}
    section = get_object_or_404(Section, pk=pk)
    print(section)
    context_dict['section'] = section
    return render(request, 'students/resources.html', context=context_dict)

def AssignmentsView(request, pk):
    context_dict = {}
    section = get_object_or_404(Section, pk=pk)
    print(section)
    context_dict['section'] = section
    return render(request, 'students/assignments.html', context=context_dict)

class AssignmentSubmissionCreateView(CreateView):
    model = AssignmentSubmission
    form_class = AssignmentSubmissionForm
    template_name = "students/assignmentsubmission.html"

    def form_valid(self, form):
        form.instance.assignment = get_object_or_404(Assignment, pk=self.kwargs['pk'])
        form.instance.student = self.request.user.students
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('students:assignments', kwargs={'pk':Assignment.objects.get(pk=self.kwargs['pk']).section.pk})

def MyAssignmentView(request, pk):
    context_dict = {}
    student = request.user.students
    assignment = Assignment.objects.get(pk=pk)
    
    if AssignmentSubmission.objects.filter(assignment=assignment).filter(student=student).exists():
        context_dict['assignment'] = assignment
        context_dict['submission'] = AssignmentSubmission.objects.filter(assignment=assignment).filter(student=student)[0]
        context_dict['assignmentfilename'] = context_dict['submission'].file.name.split('/')[-1]
        return render(request, template_name='students/my_assignment.html', context=context_dict)
    else:
        return redirect('students:submit_assignment', pk=pk)

class AssignmentSubmissionDeleteView(DeleteView):
    model = AssignmentSubmission
    template_name = "students/deletesubmission.html"
    
    def get_success_url(self):
        return reverse('students:assignments', kwargs={'pk':self.object.assignment.section.pk})

def joinClassroomView(request):
    form = JoinClassroomForm()
    
    if request.method == 'POST':
        form = JoinClassroomForm(request.POST)
        
        if form.is_valid():
            code = form.cleaned_data['code']
            print(code)
            if Classroom.objects.filter(code=code).exists():
                print('Exists', form.cleaned_data['code'])
                
                if request.user.students.classrooms.filter(code=code).exists():
                    print('User already a member')
                    return HttpResponseRedirect(reverse('students:dashboard'))
                else:
                    print('User not a member')
                    request.user.students.classrooms.add(Classroom.objects.filter(code=code).first())
                    print('User joined the classroom')
                    return HttpResponseRedirect(reverse('students:dashboard')) 
            else:
                print('Classroom dosent exist')
    return render(request, 'students/join_classroom.html', {'form':form})


def LeaveClassroomView(request,code):
    request.user.students.classrooms.remove(Classroom.objects.filter(code=code).first())
    return HttpResponseRedirect(reverse('students:dashboard'))

def view_grade(request, pk):
    assignment_obj = Assignment.objects.get(id=pk)
    studen_obj = Student.objects.get(user=request.user)
    ass_obj = AssignmentSubmission.objects.get(assignment=assignment_obj, student=studen_obj)
    return render(request, 'students/grade.html', {'ass_obj':ass_obj, 'assignment':assignment_obj})

students/templates/students/assignments.html
{% extends 'students/base.html' %}

{% load chk_date %}

<!-- Title Heading -->
{% block title %}Resources{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">
    <h1>{{section.classroom.subject|upper}} : Assignments</h1>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Duplicate this -->
    <div>
        <!-- Start: Collapsible Card -->
        {% for assignment in section.assignments.all|dictsortreversed:"created_timestamp" %}
        <div class="shadow card"><a class="btn btn-link text-left card-header font-weight-bold" data-toggle="collapse" aria-expanded="false" aria-controls="collapse-4-{{assignment.pk|slugify}}" href="#collapse-4-{{assignment.pk|slugify}}" role="button">{{assignment.title}}</a>
            <div class="collapse" id="collapse-4-{{assignment.pk|slugify}}">
                <div class="card-body">
                    <div class="alert alert-danger" role="alert"><span><strong>Deadline :&nbsp; {{assignment.deadline|date:"M d, Y"}}</strong></span></div>
                    <p class="m-0">{{assignment.text|linebreaksbr}}</p>
                    <!-- Start: break 4.0 -->
                    <!-- End: break 4.0 -->
                    <hr>
                    <div class="row">
                        <div class="col text-center">
                            {% if assignment.file %}
                            <!-- Start: Split Button Success -->
                            <a class="btn btn-success btn-icon-split" role="button" href="{{assignment.file.url}}" download>
                                <span class="text-white-50 icon">
                                    <i class="fas fa-arrow-circle-down"></i>
                                </span>
                                <span class="text-white text">Download Assignment</span>
                            </a>
                            <!-- End: Split Button Success -->
                            {% endif %}
                        </div>

                        <div class="col text-center">
                            <!-- Start: Split Button Info -->
                            {% now "Y-m-d" as todays_date %}
                            {% if not todays_date > assignment.deadline|date:"Y-m-d" %}
                            <a class="btn btn-info btn-icon-split" role="button" 
                                href="{% url 'students:my_assignment' pk=assignment.pk %}">
                                <span class="text-white-50 icon">
                                    <i class="fas fa-info-circle"></i>
                                </span>
                                <span class="text-white text">Manage Submission</span>
                            </a>
                            {% endif %}
                            <!-- End: Split Button Info -->
                        </div>

                        <div class="col text-center">
                            <!-- Start: Split Button Info -->
                            {% now "Y-m-d" as todays_date %}
                            
                            <a class="btn btn-info btn-icon-split" role="button" 
                                href="{% url 'students:view_grade' pk=assignment.pk %}">
                                <span class="text-white-50 icon">
                                    <i class="fas fa-info-circle"></i>
                                </span>
                                <span class="text-white text">View Grade</span>
                            </a>
                            <!-- End: Split Button Info -->
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- End: Collapsible Card -->
        <!-- Start: break 4.0 --><br>
        <!-- End: break 4.0 -->
        {% endfor %}
    </div>
    <!-- End: Duplicate this -->
</div>


{% endblock content %}

students/templates/students/assignmentsubmission.html
{% extends 'students/base.html' %}

<!-- Load Static -->
{% load static %}

<!-- Title Heading -->
{% block title %}Resources{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">
    <!-- Start: Basic Card -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="text-primary m-0 font-weight-bold">Assignment Title</h6>
        </div>
        <div class="card-body">
            <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button><span><strong>Deadline : 25 April, 2022</strong></span>
            </div>
            <!-- Start: if loop -->
            <div>
                <!-- Start: Forgotten Password Form -->
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-2">Upload your File....</h4>
                                    </div>
                                    <form class="user" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <div class="custom-file">
                                                {{form.file}}

                                                <label class="custom-file-label" for="customFile">Choose file</label>
                                            </div>
                                        </div>
                                        <button class="btn btn-primary btn-block text-white btn-user" type="submit">Submit</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End: Forgotten Password Form -->
            </div>
            <!-- End: if loop -->
        </div>
    </div>
    <!-- End: Basic Card -->
</div>

<script>
    document.getElementById('id_file').className += " custom-file-input";
</script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<script>
    // Add the following code if you want the name of the file appear on select
    $(".custom-file-input").on("change", function() {
        var fileName = $(this).val().split("\\").pop();
        $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });
</script>


{% endblock content %}

students/templates/students/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}Student Dashboard{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'students/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IM+Fell+Great+Primer+SC&amp;display=swap" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'students/fonts/fontawesome5-overrides.min.css' %}" />
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{% url 'students:dashboard' %}">
                    <div class="sidebar-brand-icon"><i class="fas fa-users"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>Student</span></div>
                </a>
                <hr class="sidebar-divider my-0" />
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    {% for room in user.students.classrooms.all %}
                    <!-- Start: Dupliacte this -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:classroom_detail' code=room.code %}"><i
                                class="fa fa-book"></i><span>{{room.subject|upper}}</span></a>
                    </li>
                    <!-- End: Dupliacte this -->
                    {% endfor %}
                </ul>
                <div class="text-center d-none d-md-inline">
                    <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid">
                        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button">
                            <i class="fas fa-bars"></i>
                        </button>
                        <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <div class="input-group">
                                <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ..." />
                                <div class="input-group-append">
                                    <button class="btn btn-primary py-0" type="button">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <ul class="navbar-nav flex-nowrap ml-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto navbar-search w-100">
                                        <div class="input-group">
                                            <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ..." />
                                            <div class="input-group-append">
                                                <button class="btn btn-primary py-0" type="button">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span class="d-none d-lg-inline mr-2 text-gray-600 small">{{user.first_name|upper}}
                                        {{user.last_name|upper}}</span><img class="border rounded-circle img-profile"
                                            src="{% static 'students/img/avatars/avatar5.jpeg' %}" /></a>
                                    <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                        <a class="dropdown-item" href="{% url 'students:dashboard' %}"><i
                                                class="fas fa-inbox fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Dashboard</a>
                                                <a class="dropdown-item" href="{% url 'students:join_classroom' %}"><i
                                                class="fas fa-warehouse fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Join
                                            Classroom</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                                class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- START CONTENT BLOCK -->
                {% block content %}

                {% endblock content %}
                <!-- END CONTENT BLOCK -->
            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright">
                        <span>Copyright © LMS 2022</span>
                    </div>
                </div>
            </footer>
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'students/js/theme.js' %}"></script>
</body>

</html>

students/templates/students/classroom_detail.html
{% extends 'students/base.html' %}

<!-- Title Heading -->
{% block title %}Classroom Detail{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">
    <h1 style="font-weight: bold;">{{ classroom.subject|upper }}</h1>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Duplicate me -->
    {% for section in classroom.sections.all %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="text-secondary m-0 font-weight-bold">{{section.title}}</h6>
        </div>
        <div class="card-body">
            <!-- Start: Split Button Success -->
            <a class="btn btn-success btn-icon-split" role="button" style="margin: 5px;" href="{% url 'students:resources' pk=section.pk %}"><span class="text-white-50 icon"><i class="far fa-calendar-check"></i></span><span class="text-white text">Resources</span></a>
            <!-- End: Split Button Success -->
            <!-- Start: Split Button Danger -->
            <a class="btn btn-danger btn-icon-split" role="button" style="margin: 5px;" href="{% url 'students:assignments' pk=section.pk %}"><span class="text-white-50 icon"><i class="far fa-file-archive"></i></span><span class="text-white text">Assignments</span></a>
            <!-- End: Split Button Danger -->
        </div>
    </div>
    {% endfor %}
    <!-- End: Duplicate me -->
</div>

{% endblock content %}

students/templates/students/dashboard.html
{% extends 'students/base.html' %}

<!-- Title Heading -->
{% block title %}Student Dashboard{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">
    <h1>Classrooms</h1>
    <!-- Start: break 4.0 --><br />
    <!-- End: break 4.0 -->
    <!-- Start: Dropdown Card -->
    {% for classroom in user.students.classrooms.all %}
    <div class="card shadow mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h6 class="text-primary m-0 font-weight-bold">
                {{ classroom.subject|upper }}
            </h6>
            <div class="dropdown no-arrow">
                <button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-toggle="dropdown" type="button">
                    <i class="fas fa-ellipsis-v text-gray-400"></i>
                </button>
                <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in">
                    <a class="dropdown-item text-danger" href="{% url 'students:leave_classroom' code=classroom.code %}">&nbsp;Leave</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <p class="m-0">Classroom code : {{ classroom.code }}<br /></p>
            <!-- Start: break 4.0 --><br />
            <!-- End: break 4.0 -->
            <!-- Start: Split Button Primary -->
            <a class="btn btn-primary btn-icon-split" role="button" href="{% url 'students:classroom_detail' code=classroom.code %}">
                <span class="text-white-50 icon">
                    <i class="far fa-folder"></i>
                </span>
                <span class="text-white text">Manage</span></a>
            <!-- End: Split Button Primary -->
        </div>
    </div>
    {% endfor %}
    <!-- End: Dropdown Card -->
</div>

<!-- End Content Block -->
{% endblock content %}

students/templates/students/deletesubmission.html
{% extends 'students/base.html' %}

<!-- Load Static -->
{% load static %}

<!-- Title Heading -->
{% block title %}Resources{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form}}
        <button type="submit" class="form-button btn btn-danger">Submit</button>
    </form>

</div>
{% endblock content %}

students/templates/students/grade.html
{% extends 'students/base.html' %}

<!-- Load Static -->
{% load static %}

<!-- Title Heading -->
{% block title %}Resources{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">
    <!-- Start: Basic Card -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="text-primary m-0 font-weight-bold">{{assignment.title}}</h6>
        </div>
        <div class="card-body">

            <!-- Start: Else Loop -->
            <div>
                {% if ass_obj.grade != "F" %}
                    <div class="alert alert-success" role="alert">
                        <span>
                            <strong>Grade is : {{ass_obj.grade}}</strong>
                            <br>
                        </span>
                    </div>
                {% else %}
                    <div class="alert alert-danger" role="alert">
                        <span>
                            <strong>Grade is : {{ass_obj.grade}}</strong>
                            <br>
                        </span>
                    </div>
                {% endif %}
            </div>
            <!-- End: Else Loop -->
        </div>
    </div>
    <!-- End: Basic Card -->
</div>


{% endblock content %}

students/templates/students/my_assignment.html
{% extends 'students/base.html' %}

<!-- Load Static -->
{% load static %}

<!-- Title Heading -->
{% block title %}Resources{% endblock title %}

<!-- Start Content Block -->
{% block content %}

<div class="container-fluid">
    <!-- Start: Basic Card -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="text-primary m-0 font-weight-bold">{{assignment.title}}</h6>
        </div>
        <div class="card-body">
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <span>
                    <strong>Deadline : {{assignment.deadline|date:"M d, Y"}}</strong>
                </span>
            </div>

            <!-- Start: Else Loop -->
            <div>
                <div class="alert alert-success" role="alert">
                    <span>
                        <strong>Submitted on : {{submission.submission_timestamp|date:"M d, Y"}}</strong>
                        <br>
                    </span>
                </div>
                <div class="row">
                    <div class="col">
                        <input class="form-control-lg form-control-user" type="text" id="exampleFirstName-1" placeholder="File Name" name="first_name" value="{{assignmentfilename}}" disabled="" readonly="" style="padding: 16px 16px;margin: 10px;width: 100%;">
                    </div>
                    <div class="col align-self-center">
                        <div class="row">
                            <div class="col-auto">
                                <!-- Start: Split Button Success -->
                                <a class="btn btn-success btn-lg btn-icon-split" role="button" href="{{submission.file.url}}" download>
                                    <span class="text-white-50 icon">
                                        <i class="fas fa-download"></i>
                                    </span>
                                    <span class="text-white text">Download</span>
                                </a>
                                <!-- End: Split Button Success -->
                            </div>
                            <div class="col">
                                <!-- Start: Split Button Danger -->
                                <a class="btn btn-danger btn-lg btn-icon-split" role="button" href="{% url 'students:delete_submission' pk=submission.pk %}">
                                    <span class="text-white-50 icon">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                    <span class="text-white text">Delete</span>
                                </a>
                                <!-- End: Split Button Danger -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End: Else Loop -->
        </div>
    </div>
    <!-- End: Basic Card -->
</div>


{% endblock content %}