accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, StudentCreateView, StreamView, TeacherCreateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('', IndexView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('signup/student/stream/', StreamView.as_view(template_name = "accounts/student_stream.html"), name='student_stream'),
    path('signup/student/<int:stream_pk>/', StudentCreateView.as_view(), name='student_signup'),
    
    path('signup/teacher/stream/', StreamView.as_view(template_name = "accounts/teacher_stream.html"), name='teacher_stream'),
    path('signup/teacher/<int:stream_pk>/', TeacherCreateView.as_view(), name='teacher_signup'),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mylms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", view=HomeView.as_view(),name='home'),
    path('dashboard/', DashboardView, name='dashboard'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('students/', include('students.urls', namespace='students')),
    path('teachers/', include('teachers.urls', namespace='teachers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

teachers/urls.py
from django.urls import include, path
from .views import (DashboardView, 
                    ClassroomCreateView, 
                    ClassroomDeleteView, 
                    ClassroomDetailView, 
                    ResourcesView,
                    SectionCreateView,
                    AssignmentsView,
                    SectionDeleteView,
                    ResourceCreateView,
                    ResourceDeleteView,
                    AssignmentCreateView,
                    AssignmentDeleteView,
                    AssignmentSubmissionsView,
                    ClassroomStudentsView,
                    assign_grade,
                )

app_name = 'teachers'

urlpatterns = [
    path('',                                DashboardView.as_view(),        name='dashboard'),
    path('classroom/add/',                  ClassroomCreateView.as_view(),  name='add_classroom'),
    path('classroom/<slug:code>/delete/',   ClassroomDeleteView.as_view(),  name='delete_classroom'),
    path('classroom/<slug:code>/',          ClassroomDetailView,            name='classroom_detail'),
    path('classroom/<slug:code>/students/', ClassroomStudentsView,          name='classroom_students'),
    path('classroom/<slug:code>/add/',      SectionCreateView.as_view(),    name='add_section'),
    path('section/<int:pk>/delete/',        SectionDeleteView.as_view(),    name='delete_section'),
    path('resources/<int:pk>/',             ResourcesView,                  name='resources'),
    path('resources/<int:pk>/add/',         ResourceCreateView.as_view(),   name='add_resource'),
    path('resources/delete/<int:pk>/',      ResourceDeleteView.as_view(),   name='delete_resource'),
    path('assignments/<int:pk>/',           AssignmentsView,                name='assignments'),
    path('assignments/<int:pk>/add/',       AssignmentCreateView.as_view(), name='add_assignment'),
    path('assignments/delete/<int:pk>/',    AssignmentDeleteView.as_view(), name='delete_assignment'),
    path('submissions/<int:pk>/',           AssignmentSubmissionsView,      name='assignment_submissions'),
    path('assign_grade/<int:ass_id>/<int:sub_id>/<grade>/',  assign_grade,  name="assign_grade"),
]

teachers/models.py
from django.db import models

# Create your models here.

teachers/forms.py
from accounts.models import Classroom,Teacher, Section, Resource,Assignment,AssignmentSubmission
from django import forms

class ClassroomForm(forms.ModelForm):
    
    class Meta:
        model = Classroom
        exclude = ('teacher',)

class SectionForm(forms.ModelForm):
    
    class Meta:
        model = Section
        # fields = '__all__'
        exclude = ("classroom",)

class ResourceForm(forms.ModelForm):
    
    class Meta:
        model = Resource
        # fields = '__all__'
        exclude = ("section",)

class AssignmentForm(forms.ModelForm):
    
    class Meta:
        model = Assignment
        exclude = ("section",)
        widgets = {
            'deadline' : forms.SelectDateWidget
        }

teachers/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DeleteView, DetailView
from accounts.models import Classroom,Teacher,User,Section, Resource,Assignment,AssignmentSubmission
from .forms import ClassroomForm, SectionForm,ResourceForm, AssignmentForm
from accounts.passtests import StudentTestMixin, TeacherTestMixin


# Create your views here.

class DashboardView(TeacherTestMixin,TemplateView):
    template_name = "teachers/dashboard.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['classrooms'] = self.request.user.teachers.classrooms.all()
        return context

def add_classroom(request):
    form = ClassroomForm()

    def form_valid(self, form):
        classroom = form.save(commit=False)
        classroom.teacher = Teacher.objects.get(user=self.request.user.teachers)
        classroom.save()
        return HttpResponseRedirect(self.get_success_url())    

class ClassroomCreateView(CreateView):
    model = Classroom
    form_class = ClassroomForm
    template_name = "teachers/addclassroom.html"
    
    def form_valid(self, form):
        form.instance.teacher = self.request.user.teachers
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('teachers:dashboard')

class ClassroomDeleteView(DeleteView):
    model = Classroom
    template_name = "teachers/deleteclassroom.html"

    # Should match the value after ':' from url <slug:the_slug>
    slug_url_kwarg = 'code'
    
    # Should match the name of the slug field on the model 
    slug_field = 'code' # DetailView's default value: optional
    
    def get_success_url(self):
        return reverse('teachers:dashboard')

def ClassroomDetailView(request,code):
    context_dict = {}
    room = get_object_or_404(Classroom, code=code)
    context_dict['classroom'] = room
    return render(request, 'teachers/classroom_detail.html', context=context_dict)

class SectionCreateView(CreateView):
    model = Section
    form_class = SectionForm
    template_name = "teachers/add_section.html"

    def form_valid(self, form):
        form.instance.classroom = get_object_or_404(Classroom, code=self.kwargs['code'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('teachers:classroom_detail', kwargs={'code':self.kwargs['code']})

class SectionDeleteView(DeleteView):
    model = Section
    template_name = "teachers/delete_section.html"
    
    def get_success_url(self):
        return reverse('teachers:classroom_detail', kwargs={'code':self.object.classroom.code})

def ResourcesView(request, pk):
    context_dict = {}
    section = get_object_or_404(Section, pk=pk)
    print(section)
    context_dict['section'] = section
    return render(request, 'teachers/resources.html', context=context_dict)

class ResourceCreateView(CreateView):
    model = Resource
    form_class = ResourceForm
    template_name = "teachers/add_resource.html"
    
    def form_valid(self, form):
        form.instance.section = get_object_or_404(Section, pk=self.kwargs['pk'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('teachers:resources', kwargs={'pk':self.kwargs['pk']})

class ResourceDeleteView(DeleteView):
    model = Resource
    template_name = "teachers/delete_resource.html"
   
    def get_success_url(self):
        return reverse('teachers:resources', kwargs={'pk':self.object.section.pk})


def AssignmentsView(request, pk):
    context_dict = {}
    section = get_object_or_404(Section, pk=pk)
    print(section)
    context_dict['section'] = section
    return render(request, 'teachers/assignments.html', context=context_dict)


class AssignmentCreateView(CreateView):
    model = Assignment
    form_class = AssignmentForm
    template_name = "teachers/add_assignment.html"
    
    def form_valid(self, form):
        form.instance.section = get_object_or_404(Section, pk=self.kwargs['pk'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('teachers:assignments', kwargs={'pk':self.kwargs['pk']})

class AssignmentDeleteView(DeleteView):
    model = Assignment
    template_name = "teachers/delete_assignment.html"
   
    def get_success_url(self):
        return reverse('teachers:assignments', kwargs={'pk':self.object.section.pk})

def AssignmentSubmissionsView(request,pk):
    context_dict = {}
    assignment = Assignment.objects.get(pk=pk)

    context_dict['assignment'] = assignment
    context_dict['assignment_submissions'] = AssignmentSubmission.objects.filter(assignment=assignment)
    
    return render(request, template_name='teachers/submissions.html', context=context_dict)

def ClassroomStudentsView(request,code):
    context_dict = {}
    classroom = get_object_or_404(Classroom, code=code)

    context_dict['classroom'] = classroom
    context_dict['classroom_students'] = classroom.students.all()
    
    return render(request, template_name='teachers/classroomstudents.html', context=context_dict)

def assign_grade(request, ass_id, sub_id, grade):
    sub_obj = AssignmentSubmission.objects.get(id=sub_id)
    sub_obj.grade = grade
    sub_obj.save()
    return redirect('teachers:assignment_submissions', pk=ass_id)

teachers/templates/teachers/add_assignment.html
{% extends 'teachers/base.html' %} {% load static %} {% load bootstrap4 %} {% block title %}Add Assignment{% endblock title %} {% bootstrap_messages %} {% block content %}

<h1>Add Assignment</h1>
<hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form%}
    <button type="submit" class="form-button btn btn-success">Submit</button>
    </div>
    </div>
</form>

{% endblock content %}

teachers/templates/teachers/add_resource.html
{% extends 'teachers/base.html' %} {% load static %} {% load bootstrap4 %} {% block title %}Add Resource{% endblock title %} {% bootstrap_messages %} {% block content %}

<h1>Add Resource</h1>
<hr>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form%}
    <button type="submit" class="form-button btn btn-success">Submit</button>
    </div>
    </div>
</form>

{% endblock content %}

teachers/templates/teachers/assignments.html
{% extends 'teachers/base.html' %} {% load static %} {% block title %}Assignments{% endblock title %} {% block content %}

<div class="container-fluid">
    <h1>Assignments</h1>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <div>
        <!-- Start: Split Button Warning --><a class="btn btn-warning btn-icon-split" role="button" href="{% url 'teachers:add_assignment' pk=section.pk %}"><span class="text-white-50 icon"><i class="fas fa-plus"></i></span><span class="text-white text">Add Assignment</span></a>
        <!-- End: Split Button Warning -->
    </div>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Duplicate this -->
    {% for assignment in section.assignments.all|dictsortreversed:"created_timestamp" %}
    <div>
        <!-- Start: Collapsible Card -->
        <div class="shadow card"><a class="btn btn-link text-left card-header font-weight-bold" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-4-{{assignment.pk|slugify}}" href="#collapse-4-{{assignment.pk|slugify}}" role="button">{{assignment.title}}</a>
            <div class="collapse" id="collapse-4-{{assignment.pk|slugify}}">
                <div class="card-body">
                    <div class="alert alert-danger" role="alert"><span><strong>Deadline :&nbsp; {{assignment.deadline|date:"M d, Y"}}</strong></span></div>
                    <p class="m-0">{{assignment.text|linebreaksbr}}</p>
                    <!-- Start: break 4.0 --><br>
                    <!-- End: break 4.0 -->
                    <div class="row">
                        {% if assignment.file %}
                        <div class="col text-center">
                            <!-- Start: Split Button Success --><a class="btn btn-success btn-icon-split" role="button" href="{{assignment.file.url}}" download><span class="text-white-50 icon"><i class="fas fa-arrow-circle-down"></i></span><span class="text-white text">Download Assignment</span></a>
                            <!-- End: Split Button Success -->
                        </div>
                        {% endif %}
                        <div class="col text-center">
                            <!-- Start: Split Button Info --><a class="btn btn-info btn-icon-split" role="button" href="{% url 'teachers:assignment_submissions' pk=assignment.pk %}"><span class="text-white-50 icon"><i class="fas fa-info-circle"></i></span><span class="text-white text">Submissions</span></a>
                            <!-- End: Split Button Info -->
                        </div>
                        <div class="col text-center">
                            <!-- Start: Split Button Info --><a class="btn btn-danger btn-icon-split" role="button" href="{% url 'teachers:delete_assignment' pk=assignment.pk %}"><span class="text-white-50 icon"><i class="fas fa-trash"></i></span><span class="text-white text">Delete</span></a>
                            <!-- End: Split Button Info -->
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
        <!-- End: Collapsible Card -->
        <!-- Start: break 4.0 --><br>
        <!-- End: break 4.0 -->
    </div>
    <!-- End: Duplicate this -->
    {% endfor %}
</div>

{% endblock content %}

teachers/templates/teachers/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}Base{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'teachers/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IM+Fell+Great+Primer+SC&amp;display=swap" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'teachers/fonts/fontawesome5-overrides.min.css' %}" />
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0  toggled">
            <div class="container-fluid d-flex flex-column p-0">
                <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{% url 'teachers:dashboard' %}">
                    <div class="sidebar-brand-icon"><i class="fas fa-users"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>Teacher</span></div>
                </a>
                <hr class="sidebar-divider my-0" />
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    <!-- Start: Dupliacte this -->
                    {% for classrom in user.teachers.classrooms.all %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'teachers:classroom_detail' code=classrom.code %}"><i
                                class="fa fa-book"></i><span>{{ classrom.subject }}</span></a>
                    </li>
                    <!-- End: Dupliacte this -->
                    {% endfor %}
                </ul>
                <div class="text-center d-none d-md-inline">
                    <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
                </div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid">
                        <button class="btn btn-link d-md-none rounded-circle mr-3" id="sidebarToggleTop" type="button">
                            <i class="fas fa-bars"></i>
                        </button>
                        <form class="form-inline d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <div class="input-group">
                                <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ..." />
                                <div class="input-group-append">
                                    <button class="btn btn-primary py-0" type="button">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <ul class="navbar-nav flex-nowrap ml-auto">
                            <li class="nav-item dropdown d-sm-none no-arrow">
                                <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><i class="fas fa-search"></i></a>
                                <div class="dropdown-menu dropdown-menu-right p-3 animated--grow-in" aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto navbar-search w-100">
                                        <div class="input-group">
                                            <input class="bg-light form-control border-0 small" type="text" placeholder="Search for ..." />
                                            <div class="input-group-append">
                                                <button class="btn btn-primary py-0" type="button">
                                                    <i class="fas fa-search"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <li class="nav-item dropdown no-arrow">
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-toggle="dropdown" href="#"><span
                                            class="d-none d-lg-inline mr-2 text-gray-600 small">{{user.first_name|upper}}
                                            {{user.last_name|upper}}</span><img
                                            class="rounded-circle border img-profile"
                                            src="{% static 'teachers/img/avatars/2022-04-21_15-55-27-569_lQA2GHZJMk.png' %}" /></a>
                                    <div class="dropdown-menu shadow dropdown-menu-right animated--grow-in">
                                        <a class="dropdown-item" href="{% url 'teachers:dashboard' %}"><i
                                                class="fas fa-inbox fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Dashboard</a>
                                        <a class="dropdown-item" href="{% url 'teachers:add_classroom' %}"><i
                                                class="far fa-plus-square fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Add
                                            Classroom</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                                class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>&nbsp;Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="container">
                    <!-- Body Block : START -->
                    {% block content %}

                    <!-- Body Block : END -->
                    {% endblock content %}
                </div>

            </div>
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright">
                        <span>Copyright © LMS 2022</span>
                    </div>
                </div>
            </footer>
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'teachers/js/theme.js' %}"></script>
</body>

</html>

teachers/templates/teachers/classroom_detail.html
{% extends 'teachers/base.html' %} {% load static %} {% block title %}Classroom Detail{% endblock title %} {% block content %}

<div class="container-fluid">
    <h1 style="font-weight: bold;">{{ classroom.subject|upper }}</h1>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <div>
        <!-- Start: Split Button Warning -->
        <a class="btn btn-warning btn-icon-split" role="button" href="{% url 'teachers:add_section' code=classroom.code %}"><span class="text-white-50 icon"><i
                    class="fas fa-plus"></i></span><span class="text-white text">Add Section</span></a>
        <!-- End: Split Button Warning -->
    </div>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Duplicate me -->
    {% for section in classroom.sections.all %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="text-secondary m-0 font-weight-bold">{{section.title}}</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <!-- Start: Split Button Success --><a class="btn btn-success btn-icon-split" role="button" style="margin: 5px;" href="{% url 'teachers:resources' pk=section.pk %}"><span class="text-white-50 icon"><i
                                class="far fa-calendar-check"></i></span><span
                            class="text-white text">Resources</span></a>
                    <!-- End: Split Button Success -->
                    <!-- Start: Split Button Success --><a class="btn btn-info btn-icon-split" role="button" style="margin: 5px;" href="{% url 'teachers:assignments' pk=section.pk %}"><span class="text-white-50 icon"><i
                                class="far fa-calendar-plus"></i></span><span
                            class="text-white text">Assignments</span></a>
                    <!-- End: Split Button Success -->
                </div>
                <div class="col text-right">
                    <!-- Start: Split Button Success --><a class="btn btn-danger btn-icon-split" role="button" style="margin: 5px;" href="{% url 'teachers:delete_section' pk=section.pk %}"><span class="text-white-50 icon"><i
                                class="far fa-calendar-check"></i></span><span class="text-white text">Delete</span></a>
                    <!-- End: Split Button Success -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Duplicate me -->
    {% endfor %}
</div>


{% endblock content %}

teachers/templates/teachers/dashboard.html
{% extends 'teachers/base.html' %} {% block title %}Dashboard{% endblock title %} {% block content %}

<div class="container-fluid">
    <h1>Classrooms</h1>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Dropdown Card -->
    {% for classrom in user.teachers.classrooms.all %}
    <div class="card shadow mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h6 class="text-primary m-0 font-weight-bold">{{ classrom.subject }}</h6>
            <div class="dropdown no-arrow"><button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-toggle="dropdown" type="button"><i class="fas fa-ellipsis-v text-gray-400"></i></button>
                <div class="dropdown-menu shadow dropdown-menu-right animated--fade-in"><a class="dropdown-item text-danger" href="{% url 'teachers:delete_classroom' code=classrom.code %}">Delete Classroom</a></div>
            </div>
        </div>
        <div class="card-body">
            <p class="m-0">Classroom code : {{ classrom.code }}<br></p>
            <!-- Start: break 4.0 --><br>
            <!-- End: break 4.0 -->
            <div class="row">
                <div class="col">
                    <!-- Start: Split Button Primary --><a class="btn btn-primary btn-icon-split" role="button" href="{% url 'teachers:classroom_detail' code=classrom.code %}"><span
                            class="text-white-50 icon"><i class="far fa-folder"></i></span><span
                            class="text-white text">Manage</span></a>
                    <!-- End: Split Button Primary -->
                </div>
                <div class="col text-right">
                    <!-- Start: Split Button Primary --><a class="btn btn-warning btn-icon-split" role="button" href="{% url 'teachers:classroom_students' code=classrom.code %}"><span
                            class="text-white-50 icon"><i class="far fa-user"></i></span><span
                            class="text-white text">Students</span></a>
                    <!-- End: Split Button Primary -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Dropdown Card -->
    {% endfor %}
</div>

{% endblock content %}

teachers/templates/teachers/resources.html
{% extends 'teachers/base.html' %} {% load static %} {% block title %}Resources{% endblock title %} {% block content %}

<div class="container-fluid">
    <h1>Resources</h1>
    <div>
        <!-- Start: Split Button Warning --><a class="btn btn-warning btn-icon-split" role="button" href="{% url 'teachers:add_resource' pk=section.pk %}"><span class="text-white-50 icon"><i class="fas fa-plus"></i></span><span class="text-white text">Add Resources</span></a>
        <!-- End: Split Button Warning -->
    </div>
    <!-- Start: break 4.0 --><br>
    <!-- End: break 4.0 -->
    <!-- Start: Duplicate me -->
    {% for resource in section.resources.all|dictsortreversed:"created_timestamp" %}
    <div>
        <!-- Start: Collapsible Card -->

        <div class="shadow card"><a class="btn btn-link text-left card-header font-weight-bold" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-4-{{resource.pk|slugify}}" href="#collapse-4-{{resource.pk|slugify}}" role="button">{{resource.title}}</a>
            <div class="collapse" id="collapse-4-{{resource.pk|slugify}}">
                <div class="card-body">
                    <h1 style="font-size: 14px;font-weight: bold;">{{resource.created_timestamp|date:"M d, Y"}}</h1>
                    <hr>
                    <p class="m-0">{{resource.text|linebreaksbr}}</p>
                    <!-- Start: break 4.0 --><br>
                    <!-- End: break 4.0 -->
                    <div class="row">
                        {% if resource.file %}
                        <div class="col">
                            <!-- Start: Split Button Success --><a class="btn btn-success btn-icon-split" role="button" href="{{resource.file.url}}" download><span class="text-white-50 icon"><i class="fas fa-arrow-circle-down"></i></span><span class="text-white text">Download Resource</span></a>
                            <!-- End: Split Button Success -->
                        </div>
                        {% endif %}
                        <div class="col text-right">
                            <!-- Start: Split Button Success --><a class="btn btn-danger btn-icon-split" role="button" href="{% url 'teachers:delete_resource' pk=resource.pk %}"><span class="text-white-50 icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-trash-fill">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"></path>
                                    </svg></span><span class="text-white text">Delete</span></a>
                            <!-- End: Split Button Success -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End: Collapsible Card -->
        <!-- Start: break 4.0 --><br>
        <!-- End: break 4.0 -->
    </div>
    <!-- End: Duplicate me -->
    {% endfor %}
</div>


{% endblock content %}