accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView, StudentCreateView, StreamView, TeacherCreateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    path('', IndexView.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html',redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    
    path('signup/student/stream/', StreamView.as_view(template_name = "accounts/student_stream.html"), name='student_stream'),
    path('signup/student/<int:stream_pk>/', StudentCreateView.as_view(), name='student_signup'),
    
    path('signup/teacher/stream/', StreamView.as_view(template_name = "accounts/teacher_stream.html"), name='teacher_stream'),
    path('signup/teacher/<int:stream_pk>/', TeacherCreateView.as_view(), name='teacher_signup'),
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mylms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView, DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", view=HomeView.as_view(),name='home'),
    path('dashboard/', DashboardView, name='dashboard'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('students/', include('students.urls', namespace='students')),
    path('teachers/', include('teachers.urls', namespace='teachers')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import CharField
from django.urls import reverse
from django.utils import timezone, text
from django.core.validators import MaxValueValidator, MinValueValidator
import os
import datetime
import random
import string


def _(something):
    return something


class User(AbstractUser):
    is_student = models.BooleanField('student status', default=False)
    is_teacher = models.BooleanField('teacher status', default=False)


class Stream(models.Model):

    name = models.CharField(
        _("Stream Name"),
        max_length=250,
        blank=False,
        unique=True)

    class Meta:
        verbose_name = _("stream")
        verbose_name_plural = _("streams")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("stream_detail", kwargs={"pk": self.pk})


class Class(models.Model):

    stream = models.ForeignKey(
        "Stream",
        on_delete=models.CASCADE,
        related_name="classes",
        blank=False)

    name = models.CharField(
        _("Class Name"),
        max_length=250,
        blank=False,
        unique=True)

    semester = models.PositiveIntegerField(
        blank=False,
        default=1,
        validators=[
            MaxValueValidator(8),
            MinValueValidator(1)
        ]
    )

    year = models.PositiveIntegerField(
        blank=False,
        default=2022,
        validators=[
            MaxValueValidator(2030),
            MinValueValidator(2015)
        ]
    )

    class Meta:
        verbose_name = _("class")
        verbose_name_plural = _("classes")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("class_detail", kwargs={"pk": self.pk})


class Teacher(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='teachers')

    stream = models.ForeignKey(
        "Stream",
        on_delete=models.CASCADE,
        related_name="teachers",
        blank=False)

    class Meta:
        verbose_name = _("teacher")
        verbose_name_plural = _("teachers")

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("teacher_detail", kwargs={"pk": self.pk})

def random_string(size=8, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

class Classroom(models.Model):

    teacher = models.ForeignKey(
        "Teacher",
        on_delete=models.CASCADE,
        blank=False,
        related_name='classrooms')

    subject = models.CharField(
        _("Subject Name"),
        max_length=50,
        blank=False)

    code = models.SlugField(
        _("Subject Code"),
        max_length=10,
        default=random_string,
        unique=True)

    semester = models.PositiveIntegerField(
        blank=False,
        default=1,
        validators=[
            MaxValueValidator(8),
            MinValueValidator(1)
        ]
    )

    created_timestamp = models.DateTimeField(
        default=timezone.now,
        editable=False)

    class Meta:
        verbose_name = _("Classroom")
        verbose_name_plural = _("Classrooms")

    def __str__(self):
        return self.code

    def get_absolute_url(self):
        return reverse("Classroom_detail", kwargs={"pk": self.pk})


class Student(models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='students')

    current_class = models.ForeignKey(
        "Class",
        verbose_name=_("Class"),
        on_delete=models.CASCADE,
        blank=False,
        related_name='students')

    roll_no = models.PositiveIntegerField(
        _("Roll No."),
        blank=False)

    student_id = models.CharField(
        _("Student ID"),
        max_length=50,
        blank=False,
        unique=True)

    classrooms = models.ManyToManyField("Classroom", related_name='students', blank=True)
    
    class Meta:
        verbose_name = _("student")
        verbose_name_plural = _("students")
        unique_together = ('roll_no', 'current_class')

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("Student_detail", kwargs={"pk": self.pk})


class Section(models.Model):

    classroom = models.ForeignKey(
        "Classroom",
        on_delete=models.CASCADE,
        blank=False,
        related_name='sections')

    title = models.CharField(
        _("section title"),
        max_length=150)

    created_timestamp = models.DateTimeField(
        default=timezone.now,
        editable=False
    )

    class Meta:
        verbose_name = _("section")
        verbose_name_plural = _("sections")

    def __str__(self):
        return f'{self.title} -> {self.classroom.subject}'

    def get_absolute_url(self):
        return reverse("section_detail", kwargs={"pk": self.pk})


def resource_rename_upload_file(instance, filename):
    ogfilename = filename.rsplit('.', 1)[0]
    ext = filename.split('.')[-1]
    filename = f'{text.slugify(instance.section.classroom)}/{text.slugify(instance.section)}/{text.slugify(instance.title)}/{text.slugify(instance.created_timestamp)}/{text.slugify(ext)}/{text.slugify(filename)}/{text.slugify(ogfilename)}.{text.slugify(ext)}' 
    print(filename)
    return os.path.join('files/resources/', filename)


class Resource(models.Model):

    title = models.CharField(
        _("resource title"),
        max_length=150)

    created_timestamp = models.DateTimeField(
        default=timezone.now,
        editable=False
    )

    text = models.TextField()

    section = models.ForeignKey(
        "Section",
        on_delete=models.CASCADE,
        related_name='resources',
        blank=False)

    file = models.FileField(
        upload_to=resource_rename_upload_file,
        blank=True,
        max_length=999)

    class Meta:
        verbose_name = _("resource")
        verbose_name_plural = _("resources")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("resource_detail", kwargs={"pk": self.pk})


def assignment_rename_upload_file(instance, filename):
    ogfilename = filename.rsplit('.', 1)[0]
    ext = filename.split('.')[-1]
    filename = f'{text.slugify(instance.section.classroom)}/{text.slugify(instance.section)}/{text.slugify(instance.title)}/{text.slugify(instance.created_timestamp)}/{text.slugify(ext)}/{text.slugify(filename)}/{text.slugify(ogfilename)}.{text.slugify(ext)}'
    print(filename)
    return os.path.join('files/assignments/', filename)


class Assignment(models.Model):

    title = models.CharField(
        _("section title"),
        max_length=150)

    section = models.ForeignKey(
        "Section",
        on_delete=models.CASCADE,
        related_name='assignments',
        blank=False)

    text = models.TextField()

    created_timestamp = models.DateTimeField(
        default=timezone.now,
        editable=False
    )

    deadline = models.DateTimeField(
        default=timezone.now,
        blank=False
    )

    file = models.FileField(
        upload_to=assignment_rename_upload_file,
        blank=True,
        max_length=999)

    class Meta:
        verbose_name = _("assignment")
        verbose_name_plural = _("assignments")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("assignment_detail", kwargs={"pk": self.pk})


def submission_rename_upload_file(instance, filename):
    ogfilename = filename.rsplit('.', 1)[0]
    ext = filename.split('.')[-1]
    filename = f'{text.slugify(instance.assignment.section.classroom)}/{text.slugify(instance.assignment.section)}/{text.slugify(instance.assignment.title)}/{text.slugify(instance.student)}/{text.slugify(ext)}/{text.slugify(filename)}/{text.slugify(ogfilename)}.{text.slugify(ext)}'
    print(filename)
    return os.path.join('files/assignment_submission/', filename)



class AssignmentSubmission(models.Model):

    GRADE_CHOICES = (
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("C", "C"),
        ("C", "C"),
    )

    student = models.ForeignKey(
        "Student", 
        verbose_name=_("Submitted by"), 
        on_delete=models.CASCADE, 
        related_name='assignment_submissions',
        blank=False)
    
    assignment = models.ForeignKey(
        "Assignment", 
        on_delete=models.CASCADE,
        related_name='assignment_submissions',
        blank=False)

    file = models.FileField(
        upload_to=submission_rename_upload_file,
        blank=False,
        max_length=999)

    submission_timestamp = models.DateTimeField(
        default=timezone.now,
        editable=False
    )

    grade = models.CharField(
        max_length=200, 
        null=True, 
        blank=True
    )
    
    class Meta:
        verbose_name = _("assignmentsubmission")
        verbose_name_plural = _("assignmentsubmissions")
        unique_together = ('student', 'assignment')

    def __str__(self):
        return f'{self.assignment} -> {self.student}'

    def get_absolute_url(self):
        return reverse("assignmentsubmission_detail", kwargs={"pk": self.pk})

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import Student, User, Teacher, Class, Classroom
 

class StudentForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        self.stream = kwargs.pop('stream')
        print('stream is ', self.stream)
        super(StudentForm,self).__init__(*args,**kwargs)
        
        if Class.objects.all().exists():
            self.fields['current_class'].queryset = Class.objects.filter(stream=self.stream).order_by('name')

    email = forms.EmailField(label='Email', required=True)
    
    first_name = forms.CharField(
        label='First Name', max_length=250, required=True)
    
    last_name = forms.CharField(
        label='Last Name', max_length=250, required=True)
    
    current_class = forms.ModelChoiceField(queryset=None, empty_label=None, required=True)
    
    roll_no =forms.IntegerField(label='Roll No.', required=True, min_value=1, max_value=500)
    
    student_id = forms.CharField(label='Student ID', max_length=50, required=True, min_length=4)
    
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.save()
        student = Student.objects.create(
            user=user,
            current_class = self.cleaned_data['current_class'],
            roll_no = self.cleaned_data['roll_no'],
            student_id = self.cleaned_data['student_id'],   
            )
        student.save()
        return user

    def clean(self):
        cleaned_data = super().clean()
        current_class = cleaned_data.get('current_class')
        roll_no = self.cleaned_data.get('roll_no')
        student_id = self.cleaned_data.get('student_id')
        email = self.cleaned_data.get('email')
        
        # Class and Roll No. Unique Constraint Validation
        if Student.objects.filter(current_class=current_class).filter(roll_no=roll_no).exists():
            print("Roll no in class")
            raise forms.ValidationError('Student with Roll No. already exists.')
        
        # Student id validation
        if Student.objects.filter(student_id=student_id).exists():
            print("Student ID exists")
            raise forms.ValidationError('Student with Student ID already exists.')
        
        # Email Validations
        if User.objects.filter(email=email).exists():
            print("Email exists")
            raise forms.ValidationError('User with Email already exists.')


class TeacherForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        self.stream = kwargs.pop('stream')
        print('stream is ', self.stream)
        print(type(self.stream))
        super(TeacherForm,self).__init__(*args,**kwargs)

    email = forms.EmailField(label='Email', required=True)
    
    first_name = forms.CharField(
        label='First Name', max_length=250, required=True)
    
    last_name = forms.CharField(
        label='Last Name', max_length=250, required=True)

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_teacher = True
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.save()
        teacher = Teacher.objects.create(
            user=user,
            stream = self.stream   
            )
        teacher.save()
        return user

    def clean(self):
        cleaned_data = super().clean()
        email = self.cleaned_data.get('email')

        # Email Validations
        if User.objects.filter(email=email).exists():
            print("Email exists")
            raise forms.ValidationError('User with Email already exists.')
                

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout
from django.views.generic import TemplateView, CreateView, ListView
from .models import User, Student, Teacher, Stream
from .forms import StudentForm, TeacherForm
from accounts.passtests import StudentTestMixin, TeacherTestMixin


# Create your views here.

class IndexView(TemplateView):
    template_name = "accounts/index.html"


class StudentCreateView(CreateView):
    model = User
    form_class = StudentForm
    template_name = "accounts/student_signup.html"

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('dashboard')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        print(self.kwargs)
        kwargs.update({
        'stream': Stream.objects.filter(pk=self.kwargs['stream_pk']).first(),
        })
        print(Stream.objects.filter(pk=self.kwargs['stream_pk']).first())
        return kwargs    

class StreamView(TemplateView):
    
    def get_context_data(self, **kwargs):
        context = super(StreamView, self).get_context_data(**kwargs)
        context['stream_list'] = Stream.objects.all()
        print   
        return context

class TeacherCreateView(CreateView):
    model = User
    form_class = TeacherForm
    template_name = "accounts/teacher_signup.html"

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('dashboard')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        print(self.kwargs)
        kwargs.update({
        'stream': Stream.objects.filter(pk=self.kwargs['stream_pk']).first(),
        })
        print(Stream.objects.filter(pk=self.kwargs['stream_pk']).first())
        return kwargs    

accounts/templates/accounts/base.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>{% block title %}L.M>S{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'accounts/assets/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
</head>

<body id="page-top" data-bs-spy="scroll" data-bs-target="#mainNav" data-bs-offset="57">
    <nav class="navbar navbar-light navbar-expand-lg fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">L.M.S</a><button data-bs-toggle="collapse" data-bs-target="#navbarResponsive" class="navbar-toggler navbar-toggler-right" type="button" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="fa fa-align-justify"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:student_stream' %}">Register</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <header class="text-center text-white d-flex masthead" style="background-image: url('{% static 'accounts/assets/img/home-bg.jpg' %}');">
        <!-- start -->
        {% block content %}
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <h1 class="text-uppercase">
                        <strong>Get started with <br />the learning management system</strong>
                    </h1>
                    <hr />

                </div>
            </div>
            <div class="col-lg-8 mx-auto">
                <p class="text-faded mb-5"></p>
                <a class="btn btn-primary btn-xl" role="button" href="{% url 'accounts:login' %}">Login</a>
            </div>
        </div>
        <!-- end -->
        {% endblock content %}
    </header>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 text-center mx-auto">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="my-4" />
                    <p class="mb-5">
                        Facing any problems?&nbsp; Give us a call or send us an email and we will get back to you as soon as possible!
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 text-center ms-auto">
                    <i class="fa fa-phone fa-3x mb-3 sr-contact" data-aos="zoom-in" data-aos-duration="300" data-aos-once="true"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center me-auto">
                    <i class="fa fa-envelope-o fa-3x mb-3 sr-contact" data-aos="zoom-in" data-aos-duration="300" data-aos-delay="300" data-aos-once="true"></i>
                    <p>
                        <a href="mailto:support@lmsportal.com">support@lmsportal.com</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'accounts/assets/js/bs-init.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script src="{% static 'accounts/assets/js/creative.js' %}"></script>
</body>

</html>

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %} {% block title %}Sign Up{% endblock title %} {% block content %}
<div class="container">
    <div class="jumbotron">
        <br><br><br>
        <h1 class="display-3">Sign Up!</h1>
        <br>
        <p class="lead">Create a account!</p>
        <br>
        <hr class="my-2">
        <br>
        <p>Choose your role.</p>
        <br>
        <p class="lead">
            <a class="btn btn-success btn-lg" href="{% url 'accounts:student_stream' %}" role="button">I'm a Student!</a>

            
        </p>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/login.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Login - LMS</title>
    <link rel="stylesheet" href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-4">Welcome Back!</h4>
                                    </div>
                                    <form class="user" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{form.username}}
                                            <!-- <input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address..." name="email"> -->
                                        </div>
                                        <div class="form-group">
                                            {{form.password}}
                                            <!-- <input class="form-control form-control-user" type="password" id="exampleInputPassword" placeholder="Password" name="password"> -->
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <div class="form-check">
                                                    <input class="form-check-input custom-control-input" type="checkbox" id="formCheck-1">
                                                    <label class="form-check-label custom-control-label" for="formCheck-1">Remember Me</label>
                                                </div>
                                            </div>
                                        </div><button class="btn btn-primary btn-block text-white btn-user" type="submit">Login</button>
                                        <hr>
                                    </form>
                                    <div class="text-center"><a class="small" href="#">Forgot Password?</a></div>
                                    <div class="text-center"><a class="small" href="{% url 'accounts:student_stream' %}">Create an Account!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'accounts/js/theme.js' %}"></script>
    <script>
        var form_fields = document.getElementsByTagName("input");
        form_fields[1].placeholder = "Username";
        form_fields[1].className += " form-control form-control-user";

        form_fields[2].placeholder = "Password";
        form_fields[2].className += " form-control form-control-user";
    </script>
</body>

</html>

accounts/templates/accounts/student_signup.html
<!DOCTYPE html> {% load static %}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>Register - Student</title>
    <link rel="stylesheet" href="{% static 'accounts/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" />
</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="card shadow-lg o-hidden border-0 my-5">
            <div class="card-body p-0">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h4 class="text-dark mb-4">Create an Student Account!</h4>
                            </div>
                            <form class="user" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">{{form.first_name}}</div>
                                    <div class="col-sm-6">{{form.last_name}}</div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        {{form.current_class}}
                                    </div>
                                    <div class="col-sm-6">{{form.roll_no}}</div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">{{form.username}}</div>
                                    <div class="col-sm-6">{{form.student_id}}</div>
                                </div>
                                <div class="form-group">{{form.email}}</div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">{{form.password1}}</div>
                                    <div class="col-sm-6">{{form.password2}}</div>
                                </div>
                                {{form.username.errors}} {{form.password1.errors}} {{form.password2.errors}} {{ form.non_field_errors }}

                                <button class="btn btn-primary btn-block text-white btn-user" type="submit">
                    Register Account
                  </button>
                                <hr />
                            </form>
                            <div class="text-center">
                                <a class="small" href="#">Forgot Password?</a
                  >
                </div>
                <div class="text-center">
                  <a class="small" href="{% url 'accounts:login' %}"
                    >Already have an account? Login!</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{% static 'accounts/js/theme.js' %}"></script>
    <script>
      var form_fields = document.getElementsByTagName("input");
      form_fields[1].placeholder = "First Name";
      form_fields[1].className += " form-control form-control-user";

      form_fields[2].placeholder = "Last Name";
      form_fields[2].className += " form-control form-control-user";

      form_fields[3].placeholder = "Roll No.";
      form_fields[3].className += " form-control form-control-user";

      form_fields[4].placeholder = "Username";
      form_fields[4].className += " form-control form-control-user";

      form_fields[5].placeholder = "Student ID";
      form_fields[5].className += " form-control form-control-user";

      form_fields[6].placeholder = "Email Address";
      form_fields[6].className += " form-control form-control-user";

      form_fields[7].placeholder = "Password";
      form_fields[7].className += " form-control form-control-user";

      form_fields[8].placeholder = "Repeat Password";
      form_fields[8].className += " form-control form-control-user";

      var select_fields = document.getElementsByTagName("select");
      select_fields[0].className += " custom-select";
    </script>
  </body>
</html>